nationality_name_union = Liga dos Trabalhadores da Nova Crescente
nationality_description_union = A Liga dos Trabalhadores da Nova Crescente seria formada logo após a revolta dos trabalhadores no Setor Crescente, liderada por gangues de trabalhadores e sindicatos trabalhistas que depois iriam se colectivizar sob o grupo de escala nacional conhecido como a LTNC (NCWL) atualmente. Operando em ideais socialistas e priorizando liberdade para todos, eles tendem a ser vistos como perigosamente inocentes pela maioria das opiniões.

nationality_name_empire = Mandato Solar Divino
nationality_description_empire = Criados após a dissolução da Dominião Solariana, o Mandato Solar Divino se uniria sob ideais feudais do (supostamente) todo-poderoso Kaiser. Conquistando a maioria do espaço conhecido, os Imperiais eventualmente iriam chegar na Crescente e estagnar até uma série de rebeliões e revoluções iria enfraquecer eles até o status de poder secundario no estágio político galático de hoje.

nationality_name_american = Novo Protetorado Americano
nationality_description_american = Remontado dos restantes da União Americana da Antiga Terra, o Novo Protetorado Americano seria inicialmente formado como uma união solta de postos militares Americanos espalhados fora das extremidades do Império, que ainda estava de alcançar seu apogeu. Hoje, eles operam em seus ideais anciões de liberdade pessoal e econômica, responsável pela logistica da maioria do arsenal pesado para setores externos.

nationality_name_clarizian = Ducados Clarizenhos Livres
nationality_description_clarizian = Fundado pela até-então Governanta Ariadne Clarize, os Ducados Clarizenhos Livres seriam formados logo após a criação do Mandato Solar Divino. Quando a Coalizão Oriental-Asiática caiu, a Governanta fugiria até as extremidades sudoeste do Aglomerado Conhecido e se estabeleceria no mundo temperado de Kiraigo com sua comitiva e cidadãos, nascendo disso, os Ducados como conhecemos hoje. Subjugado pelo Império no inicio de sua vida e logo forçando sua liberdade de volta das garras Imperiais, os Ducados são uma das poucas monarquias constitucionais ainda operando no Espaço Conhecido, liderada pela Sua Majestade Rainha Isobel Clarize II.

nationality_name_coalition = A Coalizão de Estações Livres Taipenhas
nationality_description_coalition = Um dos poucos grupos taipenhos realmente locais à região, a Coalizão consiste de reinos piratas, sucateiros, corporações decadentes, gangues locais, e varios outros grupos de caráter duvidoso. Considerado pela maioria de serem ilegitimos, é, independentemente, o maior regime 'soberano' no sistema inteiro, com várias naves-mãe e estações sob seu controle.

nationality_name_authority = Autoridade Central Solar
nationality_description_authority = O mais novo poder galático na cena, a Autoridade Central Solar é o estado sucessor do Mandato Solar Divino, declarando soberania após um golpe de estado sem precedentes na capital Imperial da Terra. Usando ainda mais de narrativas de supremacia humana, o Authoritat caça e executa sofontes psiônicamente-receptivos com prejuízo e determinação teimosa, acreditando que o ato retardaria o fim do Espaço Conhecido como conhecemos. Uma nação hipermilitarizada e fascista que cobre uma área surpreendente de território, eles são a maior fonte de exilados e imigrantes no Setor.